#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups

# remove any temp pipes (messes with the packager for some reason)
rm -rf "$PROJECTR_FOLDER/settings/home/tmp.cleanable/"; mkdir -p "$PROJECTR_FOLDER/settings/home/tmp.cleanable/"

# remove previous build (not doing so makes tsc crash)
rm -rf ./out; rm -f build.vsix
# build typescript then package 
tsc -p ./ && rm -f **/*.map && vsce package -o build.vsix