#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups

tsc -p ./
# remove any temp pipes (messes with the packager for some reason)
rm -rf "$PROJECTR_FOLDER/settings/home/tmp.cleanable/"
# then package 
vsce package -o build.vsix